### ISSUE TITLE
Write a initial guide

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#71]
I create this issue issue to track the biggest missing pieces of documentation that are required to publish an "initial version" of the guide.

(Thanks @faassen for the list)

* [x] How to define a body type (Static, Kinematic, Dynamic and Sensor)
* [x] PhysicMaterial
* [x] Collision detection
* [ ] 2d gotchaes (incl. rotation in 2d is around the z axis.)
* [ ] Change/Define velocity, acceleration, force and impulse
* [ ] How to acces Rapier directly (#43)

**Comment by faassen** [comment]
Oh, and of course the various types of Body needs to be discussed! We need some kind of basic 3d example too but I definitely need help for that.

**Comment by jcornaz** [comment]
As there is already a form of documentation online (https://docs.rs/heron) I consider the "initial guide" to be already written.

It is by no means perfect or complete. But we can create more specific issues for what is missing or needs improvement.

**Comment by Hellzbellz123** [comment]
an example of using  a sensor would be super helpful, something like a simple box that can move into 2 sensors triggering 2 separate things. ie sensor_a opening door_a while sensor_b opens door_b
